### ISSUE TITLE
[BUG] dead disconnection

### ISSUE THREAD

**Issue by jerome6994** [vincentwolsink/home_assistant_enphase_envoy_installer#48] opened 2023-07-19 15:46 UTC
Good morning
I just installed the integration on Home Assistant and great job for the community bravo.
On the other hand, it seems that at times there are disconnections because at times my entities are inaccessible and my templates in error then it comes back without doing anything, then it starts again like this all day!
Is there a setting to be made in particular to make it communicate more fluidly? is there a way to have if short disconnection the previous info in retain at least? If disconnection is abnormally long ok to have an unknown value for example

I have this :
![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/66921143/510696ee-25b7-4244-8084-9f96bba3a491)

after that :
![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/66921143/9d6ea34e-7842-450a-ae72-91bdd78906a3)

or that 
![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/66921143/7e98ed2e-8835-4eb3-a3b3-ffd1e9a74a86)

**Comment by vincentwolsink** [comment] 2023-07-19 18:23
Hi! Do you maybe have both an IPv4 and IPv6 address assigned to your Envoy?

**Comment by Yellimur** [comment] 2023-07-19 18:33
Hi,

Here exactly the same problem. After update of Enphase in HACS and restart no connect with Envoy anymore.

**Comment by jerome6994** [comment] 2023-07-19 19:19
> Hi! Do you maybe have both an IPv4 and IPv6 address assigned to your Envoy?

Good evening
I don't know how to say certain IPV4 but IPV6 normally no I haven't done anything for it.
I have a UDM-Pro router in DMZ but then the IPV6 I don't think I have activated it

**Comment by vincentwolsink** [comment] 2023-07-20 07:10
Indeed, you cannot have multiple active sessions to the Envoy. Can you maybe share your debug logs of the integration?

**Comment by jerome6994** [comment] 2023-07-20 08:22
Hello

I cut my test HA to do the observation today but it still works weird at the moment
I started the debug logs we will wait a moment to have information

![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/66921143/bfd7e2f4-d9af-4e20-9fc3-001b8048d833)

![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/66921143/26148374-7b86-4514-8875-a823703070eb)

**Comment by vincentwolsink** [comment] 2023-07-20 08:32
The reason for not doing a PR to the official HA is twofold:
1. This integration started out as an installer account only. It did not support non-installer accounts. Which will impact a lot of users of the current official integration. Also it doesn't support the D5 firmware, which the official integration does.
2. Since this integration is still in heavy development, I do not want to be bound to the HA release cycle and have to wait to release fixes and/or improvements.

**Comment by jerome6994** [comment] 2023-07-20 08:41
OK I understand
But I just saw one thing too is that the integration only supports installer accounts and not owner accounts only.

But my account is not an installer so can the disconnections come from there?

**Comment by vincentwolsink** [comment] 2023-07-20 09:05
The integration nowadays supports Installer, DIY and owner accounts. When using with an owner account there is less information available, and please make sure to check the owner account option during setup or via the configuration button afterwards, to prevent useless data lookups.

**Comment by jerome6994** [comment] 2023-07-20 12:06
I had not checked the box circled in red

![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/66921143/37ba9cd4-bdfc-43f7-a890-a71f6aeb2a55)

**Comment by vincentwolsink** [comment] 2023-07-23 10:22
Looking at your screenshots you seem to have a DIY account and you should not tick that box. If the issue is not fixed yet, can you please share your debug logs?

**Comment by jerome6994** [comment] 2023-07-23 19:08
Good evening
Thanks for your feedback.

So I waited a bit but on Friday I moved on to another less rich but stable integration while waiting for yours to evolve, I hope in the right direction for me. 

My installation was done by a company. I didn't do anything myself!

Then I have two size concerns!
I don't know where to find the integration logs! I've never needed to watch this kind of thing so I want to have the process.
Then, are there still traces due to the change of integration?
Then I can also come back to your integration, let it run for a few days and send you fresh traces.

**Comment by jerome6994** [comment] 2023-07-23 21:10
it still picks up even though I did not check the box as requested
![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/66921143/4a0e5658-b023-4b33-8a35-f906ef03ff7a)
[journal.txt](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/files/12139964/journal.txt)

**Comment by jerome6994** [comment] 2023-07-26 22:26
Hello
Today's update is worse for me!
I no longer have a connection to enphase at all

**Comment by bes-r** [comment] 2023-07-27 05:20
The beta version 0.3.1 will fix your connection issue.

**Comment by vincentwolsink** [comment] 2023-08-15 18:39
This issue seems stale. Closing it for now. Please reopen if you still encounter problems.

**Closed by vincentwolsink** 2023-08-15 18:39 UTC

**Comment by jerome6994** [comment] 2023-08-19 15:57
Hello Vincent
I'm back from vacation and I just put the integration back today.
For the moment no disconnection
The fix seems ok, I don't know what it came from but great job
